repos:
- repo: https://github.com/ambv/black
  rev: 21.5b2
  hooks:
  - id: black
    args:
    - --check
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.1
  hooks:
  - id: flake8
- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
    - id: isort
      args: [--check-only --profile black]
